baseurl = "https://archivesunleashed.org/"
languageCode = "en-us"
title = "The Archives Unleashed Project"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-2879197-28"

[params]
	# General information
	author = "The Archives Unleashed Project"
	copyright = "CC-BY"

	# Repository
	provider = "GitHub"

	#version = "1.0.0"
	logo = "images/ArchivesUnleashedLogo.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "grey"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "unleasharchives"
	github  = "archivesunleashed"
	email   = "archivesunleashed@gmail.com"

[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "About the Project"
	url    = "about-project/"
	weight = 10

[[menu.main]]
	name   = "Archives Unleashed Toolkit"
	url    = "aut/"
	weight = 15

[[menu.main]]
	name   = "Archives Unleashed Cloud"
	url    = "cloud/"
	weight = 16

[[menu.main]]
	name   = "Warclight"
	url    = "warclight/"
	weight = 18

[[menu.main]]
	name   = "Get Involved"
	url    = "get-involved/"
	weight = 30

[[menu.main]]
	name   = "Events"
	url    = "events/"
	weight = 40


[[menu.main]]
	name   = "Publications"
	url    = "publications/"
	weight = 48

[[menu.main]]
	name   = "News (on Medium.com)"
	url    = "https://news.archivesunleashed.org"
	weight = 50

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
